//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyWise
{
    using System;
    using System.Collections.Generic;
    
    public partial class messageTable
    {
        public int messageID { get; set; }
        public Nullable<int> PositivityScore { get; set; }
        public string personalized_message { get; set; }
    }
}
